
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function: - Code used to simulate the range of RT+HT protocols considered
%            in the paper
%           - Assume that the file in location 'file_path' contains the
%           parameters values that define the tumours of interest, i.e., 
%           the oxygen consumption rates, q1 and q3, the vascular volume,
%           V0, and the steady state tumour volume and oxygen
%           concentration,T0 and c0.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Import tumour information
clear all

tumours = readtable('filepath');

%% Define model parameters

 % Tumour growth parameters

        % Carrying capacity
        K = 1;

        % Anoxic O2 threshold
        c_min = 1e-2;

        % Rate of oxygen release from vasculature
        g = 5;

        % proliferation rate of undamaged tumour cells
        conv = 1e-2;
        q1 = tumours.q1;
        q3 = tumours.q3;
        q2 = conv*q3;

        % Cell oxygen consumption and proliferation rates
        q3sl = 1e-1*q3;
        q2sl = conv*q3sl;
        q1sl = 1e1*q1;

        % Cell death rates
        d1 = q2;
        d1sl = q2sl;

    % RT parameters

        % Defining the number of RT fractions, time between fractions, the
        % RT doses and dose rates

        % Total number of fractions corresponding given RT dose: 
        % 0, 1, 2, 3, 4, 5 Gy
        num_frac_RT = [0, 80, 40, 26,  20, 16]; 
        
        % 10 min irradiation
        time_treat = 10;                       

        % 1 day = 1440 min, 2 days = 2880 min, 5 days = 7200 min
        time_btw_frac_RT = [1.44e3, 2.88e3, 7.2e3];     

        % RT dose rates
        R = linspace(0,5,6)/(time_treat); 

        % RT damage rates
        l1 = 10;
        l2 = 1;
        l2sl = 1;

        % Damage repair rate
        mu = 5e-3;

        % Rate of clearance of cells killed by RT 
        eta_R = 5e-5;

        % Rate of MC
        zeta = 5e-4;
        
    % HT parameters 
            
        % High HT duration
            t_high = 60; 
       
        % Rate of HT cell kill
             b = [0, 0.001, 0.003, 0.005, 0.007, 0.009, 0.01];

        % Rate of vascular regrowth
        	 k0 = [1e-8, 1e-7, 1e-6];
        
        % Rate of dead cell (by HT) clearance
            eta_H = 5e-5;
    
        % Rate of repair inhibition by high HT
            k1 = 100*b;
            
        % Rate of reactivation of DNA repair mechanisms
            k2 = 0.001;
            
        % HT weighing factor;
           mu_v = 2.5;

    % Delay between HT and RT 
        time_btw_HT_RT = [1, 60, 240];
    
    %% Solver options
    options = odeset('AbsTol',1e-10, 'RelTol',1e-10,'NonNegative',1:8);

    %% Simulating RT+HT: HT applied before RT and RT applied 5x per week

for n = 1:size(time_btw_HT_RT,2)   
    for j = 1:size(q1,1)
        for k = 1:(size(R,2)-1)
            for l = 1:(size(b,2))
                for m = 1:size(k0,2)

                    i = 1;

                    tt = [0];
                    TT_1 = [tumours.T0(j)];
                    TT_2 = [0];
                    TT_3 = [0];
                    TT_4 = [0];
                    TT_5 = [tumours.V0(j)];
                    TT_6 = [tumours.c0(j)];
                    TT_7 = [1];
                    TT_8 = [0];

                 
                    while i <= num_frac_RT(k+1)

                        % If it's a Monday:
                        if (i == 1) || (mod(i-1,5) == 0)
                         
                            % High HT 
                            t_1 = linspace(tt(end), ...
                                           tt(end) + t_high, ...
                                           30);

                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                  TT_4(end),TT_5(end), TT_6(end), ...
                                  TT_7(end),TT_8(end)];

                            [tt_1,TT] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j), ...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(l), k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(l),k2,R(1)),t_1,IC, options);
                         
                             
                            % Between HT and RT 
                             t_2 = linspace(tt_1(end),...
                                            tt_1(end) + time_btw_HT_RT(n),...
                                            50);

                            IC_2 = [TT(end,1), TT(end,2), TT(end,3),...
                                    TT(end,4),TT(end,5), TT(end,6),...
                                    TT(end,7),TT(end,8)];

                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);
                             
                            % RT                                        
                            t_3 = linspace(tt_2(end),...
                                           tt_2(end) + time_treat, ...
                                           20);

                            IC_3 = [TTb(end,1), TTb(end,2), TTb(end,3),...
                                    TTb(end,4),TTb(end,5), TTb(end,6),...
                                    TTb(end,7),TTb(end,8)];

                            [tt_3,TTc] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j), q3(j),q3sl(j), g,...
                                         d1(j),d1sl(j),b(1), k0(m), eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(k+1)),t_3,IC_3, options);

                            
                            
                            % Post RT+HT regrowth                                     
                            t_4 = linspace(tt_3(end), tt_3(end) + ...
                                 (time_btw_frac_RT(1) - time_treat - ...
                                 t_high - time_btw_HT_RT(n)),...
                                500);

                            IC_4 =[TTc(end,1), TTc(end,2), TTc(end,3), ...
                                   TTc(end,4),TTc(end,5), TTc(end,6),...
                                   TTc(end,7),TTc(end,8)];

                            [tt_4,TTd] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_4,IC_4, options);

                            tt = vertcat(tt,[tt_1;tt_2;tt_3;tt_4]);
                            TT_1 = vertcat(TT_1, ...
                                [TT(:,1); TTb(:,1);TTc(:,1);TTd(:,1)]);
                            TT_2 = vertcat(TT_2,...
                                [TT(:,2); TTb(:,2);TTc(:,2);TTd(:,2)]);
                            TT_3 = vertcat(TT_3, ...
                                [TT(:,3); TTb(:,3);TTc(:,3);TTd(:,3)]);
                            TT_4 = vertcat(TT_4, ...
                                [TT(:,4); TTb(:,4);TTc(:,4);TTd(:,4)]);
                            TT_5 = vertcat(TT_5,...
                                [TT(:,5); TTb(:,5);TTc(:,5);TTd(:,5)]);
                            TT_6 = vertcat(TT_6, ...
                                [TT(:,6); TTb(:,6);TTc(:,6);TTd(:,6)]);
                            TT_7 = vertcat(TT_7, ...
                                [TT(:,7); TTb(:,7);TTc(:,7);TTd(:,7)]);
                            TT_8 = vertcat(TT_8, ...
                                [TT(:,8); TTb(:,8);TTc(:,8);TTd(:,8)]);


                            i = i+1;

                        else

                            % RT 
                            t_1 = linspace(tt(end),...
                                tt(end) + time_treat, ...
                                50);
                            
                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                TT_4(end),TT_5(end), TT_6(end), ...
                                TT_7(end),TT_8(end)];

                            [tt_1,TT] =  ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j), q3(j),q3sl(j), g,...
                                         d1(j),d1sl(j),b(1), k0(m), eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(k+1)),t_1,IC, options);    


                            % Post-RT tumour growth

                                if (mod(i,5) == 0) 
                                    % weekend break after a Friday fraction
                                    time_break = 2.88e3;
                                else
                                    time_break = 0; 
                                end
  
                            t_2 = linspace(tt_1(end), ...
                                 tt_1(end) + time_btw_frac_RT(1) - ...
                                 time_treat + time_break,...
                                 500);
                            
                            IC_2 =[TT(end,1), TT(end,2), TT(end,3),...
                                TT(end,4),TT(end,5), TT(end,6),...
                                TT(end,7),TT(end,8)];
                            
                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);    

                            tt = vertcat(tt,[tt_1;tt_2]);
                            TT_1 = vertcat(TT_1, [TT(:,1); TTb(:,1)]);
                            TT_2 = vertcat(TT_2, [TT(:,2); TTb(:,2)]);
                            TT_3 = vertcat(TT_3, [TT(:,3); TTb(:,3)]);
                            TT_4 = vertcat(TT_4, [TT(:,4); TTb(:,4)]);
                            TT_5 = vertcat(TT_5, [TT(:,5); TTb(:,5)]);
                            TT_6 = vertcat(TT_6, [TT(:,6); TTb(:,6)]);
                            TT_7 = vertcat(TT_7, [TT(:,7); TTb(:,7)]);
                            TT_8 = vertcat(TT_8, [TT(:,8); TTb(:,8)]);


                            i = i+1;
                        end
                    end
         
                end 
            end 
        end 
    end 
end 
%% Simulating RT+HT: HT applied before RT and RT applied 3x per week

for n = 1%:size(time_btw_HT_RT,2)   
    for j = 1%:size(q1,1)
        for k = 5%:(size(R,2)-1)
            for l = 2%:(size(b,2))
                for m = 2%:size(k0,2)

                    i = 1;

                    tt = [0];
                    TT_1 = [tumours.T0(j)];
                    TT_2 = [0];
                    TT_3 = [0];
                    TT_4 = [0];
                    TT_5 = [tumours.V0(j)];
                    TT_6 = [tumours.c0(j)];
                    TT_7 = [1];
                    TT_8 = [0];

                 
                    while i <= num_frac_RT(k+1)
                        % If it's a Monday:
                        if (i == 1) || (mod(i-1,3) == 0)
                         
                            % High HT 
                            t_1 = linspace(tt(end),tt(end) + t_high , 30);

                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                TT_4(end),TT_5(end), TT_6(end), ...
                                TT_7(end),TT_8(end)];

                           
                            [tt_1,TT] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j), ...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(l), k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(l),k2,R(1)),t_1,IC, options);
                  
                           
                             % Between HT and RT
                             
                              % Between HT and RT 
                             t_2 = linspace(tt_1(end),...
                                            tt_1(end) + time_btw_HT_RT(n),...
                                            50);

                            IC_2 = [TT(end,1), TT(end,2), TT(end,3),...
                                    TT(end,4),TT(end,5), TT(end,6),...
                                    TT(end,7),TT(end,8)];

                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);
                             
                            % RT                                        
                            t_3 = linspace(tt_2(end),...
                                           tt_2(end) + time_treat, ...
                                           20);

                            IC_3 = [TTb(end,1), TTb(end,2), TTb(end,3),...
                                    TTb(end,4),TTb(end,5), TTb(end,6),...
                                    TTb(end,7),TTb(end,8)];

                            [tt_3,TTc] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j), q3(j),q3sl(j), g,...
                                         d1(j),d1sl(j),b(1), k0(m), eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(k+1)),t_3,IC_3, options);

                                
                            
                            
                            % Post treatment effects regrowth                                     
                            t_4 = linspace(tt_3(end), ...
                                tt_3(end) + (time_btw_frac_RT(2) - ...
                                time_treat - t_high - time_btw_HT_RT(n)),...
                                500);

                            IC_4 =[TTc(end,1), TTc(end,2), TTc(end,3),...
                                TTc(end,4),TTc(end,5), TTc(end,6), ...
                                TTc(end,7),TTc(end,8)];

                            [tt_4,TTd] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_4,IC_4, options);

                            tt = vertcat(tt,[tt_1;tt_2;tt_3;tt_4]);
                            TT_1 = vertcat(TT_1, ...
                                [TT(:,1); TTb(:,1);TTc(:,1);TTd(:,1)]);
                            TT_2 = vertcat(TT_2, ...
                                [TT(:,2); TTb(:,2);TTc(:,2);TTd(:,2)]);
                            TT_3 = vertcat(TT_3,...
                                [TT(:,3); TTb(:,3);TTc(:,3);TTd(:,3)]);
                            TT_4 = vertcat(TT_4,...
                                [TT(:,4); TTb(:,4);TTc(:,4);TTd(:,4)]);
                            TT_5 = vertcat(TT_5, ...
                                [TT(:,5); TTb(:,5);TTc(:,5);TTd(:,5)]);
                            TT_6 = vertcat(TT_6, ...
                                [TT(:,6); TTb(:,6);TTc(:,6);TTd(:,6)]);
                            TT_7 = vertcat(TT_7, ...
                                [TT(:,7); TTb(:,7);TTc(:,7);TTd(:,7)]);
                            TT_8 = vertcat(TT_8, ...
                                [TT(:,8); TTb(:,8);TTc(:,8);TTd(:,8)]);



                            i = i+1;

                        else

                            % RT 
                            t_1 = linspace(tt(end),...
                                tt(end) + time_treat, ...
                                50);
                            
                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                TT_4(end),TT_5(end), TT_6(end), ...
                                TT_7(end),TT_8(end)];

                            [tt_1,TT] =  ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j), q3(j),q3sl(j), g,...
                                         d1(j),d1sl(j),b(1), k0(m), eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(k+1)),t_1,IC, options);    


                            % Post-RT tumour growth

                            
                                if (mod(i,3) == 0) 
                                    % If it's a Friday, ensure the weekend
                                    % break
                                    time_break = 1.44e3;
                                else
                                    time_break = 0; 
                                end

                           
                            t_2 = linspace(tt_1(end), ...
                                 tt_1(end) + time_btw_frac_RT(2) - ...
                                 time_treat + time_break,...
                                 500);
                            
                            IC_2 =[TT(end,1), TT(end,2), TT(end,3),...
                                TT(end,4),TT(end,5), TT(end,6),...
                                TT(end,7),TT(end,8)];
                            
                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);    

                            tt = vertcat(tt,[tt_1;tt_2]);
                            TT_1 = vertcat(TT_1, [TT(:,1); TTb(:,1)]);
                            TT_2 = vertcat(TT_2, [TT(:,2); TTb(:,2)]);
                            TT_3 = vertcat(TT_3, [TT(:,3); TTb(:,3)]);
                            TT_4 = vertcat(TT_4, [TT(:,4); TTb(:,4)]);
                            TT_5 = vertcat(TT_5, [TT(:,5); TTb(:,5)]);
                            TT_6 = vertcat(TT_6, [TT(:,6); TTb(:,6)]);
                            TT_7 = vertcat(TT_7, [TT(:,7); TTb(:,7)]);
                            TT_8 = vertcat(TT_8, [TT(:,8); TTb(:,8)]);


                            i = i+1;
                        end
                    end

                       
            
                end 
            end 
        end 
    end 
end 

%% Simulating RT+HT: HT applied before RT and RT applied 1x per week

for n = 1%:size(time_btw_HT_RT,2)   
    for j = 1%:size(q1,1)
        for k = 5%:(size(R,2)-1)
            for l = 2%:(size(b,2))
                for m = 1%:size(k0,2)

                    i = 1;

                    tt = [0];
                    TT_1 = [tumours.T0(j)];
                    TT_2 = [0];
                    TT_3 = [0];
                    TT_4 = [0];
                    TT_5 = [tumours.V0(j)];
                    TT_6 = [tumours.c0(j)];
                    TT_7 = [1];
                    TT_8 = [0];

                 
                    while i <= num_frac_RT(k+1)


                           % High HT 
                            t_1 = linspace(tt(end),tt(end) + t_high , 30);

                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                TT_4(end),TT_5(end), TT_6(end), ...
                                TT_7(end),TT_8(end)];

                           
                            [tt_1,TT] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j), ...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(l), k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(l),k2,R(1)),t_1,IC, options);
                  
                           
                             % Between HT and RT
                             
                              % Between HT and RT 
                             t_2 = linspace(tt_1(end),...
                                            tt_1(end) + time_btw_HT_RT(n),...
                                            50);

                            IC_2 = [TT(end,1), TT(end,2), TT(end,3),...
                                    TT(end,4),TT(end,5), TT(end,6),...
                                    TT(end,7),TT(end,8)];

                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);
                             
                            % RT                                        
                            t_3 = linspace(tt_2(end),...
                                           tt_2(end) + time_treat, ...
                                           20);

                            IC_3 = [TTb(end,1), TTb(end,2), TTb(end,3),...
                                    TTb(end,4),TTb(end,5), TTb(end,6),...
                                    TTb(end,7),TTb(end,8)];

                            [tt_3,TTc] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j), q3(j),q3sl(j), g,...
                                         d1(j),d1sl(j),b(1), k0(m), eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(k+1)),t_3,IC_3, options);

                             
                            % Post-RT tumour growth
                           
                            time_break = 2.88e3;        
                                                         
                            t_4 = linspace(tt_3(end), tt_3(end) + ...
                                (time_btw_frac_RT(3) - time_treat - ...
                                t_high - time_btw_HT_RT(n) + time_break),...
                                500);

                           
                            IC_4 =[TTc(end,1), TTc(end,2), TTc(end,3),...
                                TTc(end,4),TTc(end,5), TTc(end,6), ...
                                TTc(end,7),TTc(end,8)];

                            [tt_4,TTd] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_4,IC_4, options);

                            tt = vertcat(tt,[tt_1;tt_2;tt_3;tt_4]);
                            TT_1 = vertcat(TT_1, ...
                                [TT(:,1); TTb(:,1);TTc(:,1);TTd(:,1)]);
                            TT_2 = vertcat(TT_2,...
                                [TT(:,2); TTb(:,2);TTc(:,2);TTd(:,2)]);
                            TT_3 = vertcat(TT_3,...
                                [TT(:,3); TTb(:,3);TTc(:,3);TTd(:,3)]);
                            TT_4 = vertcat(TT_4, ...
                                [TT(:,4); TTb(:,4);TTc(:,4);TTd(:,4)]);
                            TT_5 = vertcat(TT_5, ...
                                [TT(:,5); TTb(:,5);TTc(:,5);TTd(:,5)]);
                            TT_6 = vertcat(TT_6, ...
                                [TT(:,6); TTb(:,6);TTc(:,6);TTd(:,6)]);
                            TT_7 = vertcat(TT_7, ...
                                [TT(:,7); TTb(:,7);TTc(:,7);TTd(:,7)]);
                            TT_8 = vertcat(TT_8, ...
                                [TT(:,8); TTb(:,8);TTc(:,8);TTd(:,8)]);



                            i = i+1;
                     

                        end 
            
                end 
            end 
        end 
    end 
end 

%% Simulating RT+HT: RT applied before HT and RT applied 5x per week

for n = 3%:size(time_btw_HT_RT,2)   
    for j = 2%1:size(q1,1)
        for k = 2%1:(size(R,2)-1)
            for l = 3%1:(size(b,2))
                for m = 2%1:size(k0,2)

                    i = 1;

                    tt = [0];
                    TT_1 = [tumours.T0(j)];
                    TT_2 = [0];
                    TT_3 = [0];
                    TT_4 = [0];
                    TT_5 = [tumours.V0(j)];
                    TT_6 = [tumours.c0(j)];
                    TT_7 = [1];
                    TT_8 = [0];

                 
                    while i <= num_frac_RT(k+1)

                        %If it's a Monday:
                        if (i == 1) || (mod(i-1,5) == 0)
                         
                            % RT
                            t_1 = linspace(tt(end),...
                                tt(end) + time_treat ,...
                                20);

                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                TT_4(end),TT_5(end), TT_6(end), ...
                                TT_7(end),TT_8(end)];

                            [tt_1,TT] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j),...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(1),k2,R(k+1)),t_1,IC, options);
                            
                            
                           
                           
                             % Between HT and RT
                             
                             t_2 = linspace(tt_1(end),...
                                 tt_1(end) + time_btw_HT_RT(n),...
                                 50);

                            IC_2 = [TT(end,1), TT(end,2), TT(end,3),...
                                TT(end,4),TT(end,5), TT(end,6),...
                                TT(end,7),TT(end,8)];

                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);
                             
                            % High HT                                        
                            t_3 = linspace(tt_2(end),...
                                tt_2(end) + t_high,...
                                30);

                            IC_3 = [TTb(end,1), TTb(end,2), TTb(end,3),...
                                TTb(end,4),TTb(end,5), TTb(end,6), ...
                                TTb(end,7),TTb(end,8)];

                            [tt_3,TTc] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j), ...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(l), k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(l),k2,R(1)),t_3,IC_3, options);
                            
                            
                            % Post RT+HT tumour growth
                           
                            
                            
                            % Post treatment effects regrowth                                     
                            t_4 = linspace(tt_3(end), ...
                                tt_3(end) + (time_btw_frac_RT(1) - ...
                                time_treat - t_high - time_btw_HT_RT(n)),...
                                500);

                            IC_4 =[TTc(end,1), TTc(end,2), TTc(end,3), ...
                                TTc(end,4),TTc(end,5), TTc(end,6), ...
                                TTc(end,7),TTc(end,8)];

                            [tt_4,TTd] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_4,IC_4, options);

                            tt = vertcat(tt,[tt_1;tt_2;tt_3;tt_4]);
                            TT_1 = vertcat(TT_1, ...
                                [TT(:,1); TTb(:,1);TTc(:,1);TTd(:,1)]);
                            TT_2 = vertcat(TT_2, ...
                                [TT(:,2); TTb(:,2);TTc(:,2);TTd(:,2)]);
                            TT_3 = vertcat(TT_3, ...
                                [TT(:,3); TTb(:,3);TTc(:,3);TTd(:,3)]);
                            TT_4 = vertcat(TT_4, ...
                                [TT(:,4); TTb(:,4);TTc(:,4);TTd(:,4)]);
                            TT_5 = vertcat(TT_5, ...
                                [TT(:,5); TTb(:,5);TTc(:,5);TTd(:,5)]);
                            TT_6 = vertcat(TT_6, ...
                                [TT(:,6); TTb(:,6);TTc(:,6);TTd(:,6)]);
                            TT_7 = vertcat(TT_7, ...
                                [TT(:,7); TTb(:,7);TTc(:,7);TTd(:,7)]);
                            TT_8 = vertcat(TT_8, ...
                                [TT(:,8); TTb(:,8);TTc(:,8);TTd(:,8)]);



                            i = i+1;

                        else
                            % RT
                            t_1 = linspace(tt(end),...
                                tt(end) + time_treat,...
                                50);
                            
                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                TT_4(end),TT_5(end), TT_6(end),...
                                TT_7(end),TT_8(end)];

                            [tt_1,TT] =  ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j),...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(1),k2,R(k+1)),t_1,IC, options);    


                            % Post-RT tumour growth
                                if (mod(i,5) == 0) 
                                    % If it's a Friday, ensure there is the
                                    % weekend break
                                    time_break = 2.88e3;
                                else
                                    time_break = 0; 
                                end

                            t_2 = linspace(tt_1(end),...
                                tt_1(end) + time_btw_frac_RT(1) ...
                                - time_treat + time_break,...
                                500);
                            
                            IC_2 =[TT(end,1), TT(end,2), TT(end,3),...
                                TT(end,4),TT(end,5), TT(end,6), ....
                                TT(end,7),TT(end,8)];
                            
                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);    

                            tt = vertcat(tt,[tt_1;tt_2]);
                            TT_1 = vertcat(TT_1, [TT(:,1); TTb(:,1)]);
                            TT_2 = vertcat(TT_2, [TT(:,2); TTb(:,2)]);
                            TT_3 = vertcat(TT_3, [TT(:,3); TTb(:,3)]);
                            TT_4 = vertcat(TT_4, [TT(:,4); TTb(:,4)]);
                            TT_5 = vertcat(TT_5, [TT(:,5); TTb(:,5)]);
                            TT_6 = vertcat(TT_6, [TT(:,6); TTb(:,6)]);
                            TT_7 = vertcat(TT_7, [TT(:,7); TTb(:,7)]);
                            TT_8 = vertcat(TT_8, [TT(:,8); TTb(:,8)]);


                            i = i+1;
                        end
                    end                    
            
                end 
            end 
        end 
    end 
end 


%% Simulating RT+HT: RT applied before HT and RT applied 3x per week


for n = 1%1:size(time_btw_HT_RT,2)   
    for j = 2%1:size(q1,1)
        for k = 5%1:(size(R,2)-1)
            for l = 2%1:(size(b,2))
                for m = 2%1:size(k0,2)

                    i = 1;

                    tt = [0];
                    TT_1 = [tumours.T0(j)];
                    TT_2 = [0];
                    TT_3 = [0];
                    TT_4 = [0];
                    TT_5 = [tumours.V0(j)];
                    TT_6 = [tumours.c0(j)];
                    TT_7 = [1];
                    TT_8 = [0];

                 
                    while i <= num_frac_RT(k+1)

                        % If it's a Monday:
                        if (i == 1) || (mod(i-1,3) == 0)
                         
                            % RT
                            t_1 = linspace(tt(end),tt(end) + time_treat , 20);

                            IC = [TT_1(end), TT_2(end), TT_3(end),TT_4(end),TT_5(end), TT_6(end), TT_7(end),TT_8(end)];

                            [tt_1,TT] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j),...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(1),k2,R(k+1)),t_1,IC, options);
                  
                           
                             % Between HT and RT
                             
                             t_2 = linspace(tt_1(end),...
                                 tt_1(end) + time_btw_HT_RT(n),...
                                 50);

                            IC_2 = [TT(end,1), TT(end,2), TT(end,3),...
                                TT(end,4),TT(end,5), TT(end,6),...
                                TT(end,7),TT(end,8)];

                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);
                             
                            % HT                                   
                            t_3 = linspace(tt_2(end),...
                                tt_2(end) + t_high,...
                                30);

                            IC_3 = [TTb(end,1), TTb(end,2), TTb(end,3),...
                                TTb(end,4),TTb(end,5), TTb(end,6), ...
                                TTb(end,7),TTb(end,8)];

                            [tt_3,TTc] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j), ...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(l), k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(l),k2,R(1)),t_3,IC_3, options);
                            
                            
                            
                            % Post treatment effects regrowth                                     
                            t_4 = linspace(tt_3(end), ...
                                tt_3(end) + (time_btw_frac_RT(2) - ...
                                time_treat - t_high - time_btw_HT_RT(n)),...
                                500);

                            IC_4 =[TTc(end,1), TTc(end,2), TTc(end,3), ...
                                TTc(end,4),TTc(end,5), TTc(end,6),...
                                TTc(end,7),TTc(end,8)];

                            [tt_4,TTd] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_4,IC_4, options);

                            tt = vertcat(tt,[tt_1;tt_2;tt_3;tt_4]);
                            TT_1 = vertcat(TT_1, ...
                                [TT(:,1); TTb(:,1);TTc(:,1);TTd(:,1)]);
                            TT_2 = vertcat(TT_2, ...
                                [TT(:,2); TTb(:,2);TTc(:,2);TTd(:,2)]);
                            TT_3 = vertcat(TT_3, ...
                                [TT(:,3); TTb(:,3);TTc(:,3);TTd(:,3)]);
                            TT_4 = vertcat(TT_4, ...
                                [TT(:,4); TTb(:,4);TTc(:,4);TTd(:,4)]);
                            TT_5 = vertcat(TT_5, ...
                                [TT(:,5); TTb(:,5);TTc(:,5);TTd(:,5)]);
                            TT_6 = vertcat(TT_6, ...
                                [TT(:,6); TTb(:,6);TTc(:,6);TTd(:,6)]);
                            TT_7 = vertcat(TT_7, ...
                                [TT(:,7); TTb(:,7);TTc(:,7);TTd(:,7)]);
                            TT_8 = vertcat(TT_8, ...
                                [TT(:,8); TTb(:,8);TTc(:,8);TTd(:,8)]);



                            i = i+1;

                        else
                            % RT
                            t_1 = linspace(tt(end),...
                                tt(end) + time_treat,...
                                50);
                            
                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                TT_4(end),TT_5(end), TT_6(end), ...
                                TT_7(end),TT_8(end)];

                            [tt_1,TT] =  ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j),...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(1),k2,R(k+1)),t_1,IC, options);    


                            % Post-RT tumour growth

                                if (mod(i,3) == 0)   
                                    % If it's a Friday, ensure there is a
                                    % weekend break
                                    time_break = 1.44e3;
                                else
                                    time_break = 0; 
                                end

                           
                            
                            t_2 = linspace(tt_1(end), ...
                                tt_1(end) + time_btw_frac_RT(2) - ...
                                time_treat + time_break,...
                                500);
                            
                            IC_2 =[TT(end,1), TT(end,2), TT(end,3), ...
                                TT(end,4),TT(end,5), TT(end,6), ...
                                TT(end,7),TT(end,8)];
                            
                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);    

                            tt = vertcat(tt,[tt_1;tt_2]);
                            TT_1 = vertcat(TT_1, [TT(:,1); TTb(:,1)]);
                            TT_2 = vertcat(TT_2, [TT(:,2); TTb(:,2)]);
                            TT_3 = vertcat(TT_3, [TT(:,3); TTb(:,3)]);
                            TT_4 = vertcat(TT_4, [TT(:,4); TTb(:,4)]);
                            TT_5 = vertcat(TT_5, [TT(:,5); TTb(:,5)]);
                            TT_6 = vertcat(TT_6, [TT(:,6); TTb(:,6)]);
                            TT_7 = vertcat(TT_7, [TT(:,7); TTb(:,7)]);
                            TT_8 = vertcat(TT_8, [TT(:,8); TTb(:,8)]);


                            i = i+1;
                        end
                    end

                   
                      
            
                end 
            end 
        end 
    end 
end 

%% Simulating RT+HT: RT applied before HT and RT applied 1x per week

for n = 3%:size(time_btw_HT_RT,2)   
    for j = 2%1:size(q1,1)
        for k = 3%1:(size(R,2)-1)
            for l = 2%1:(size(b,2))
                for m = 2%1:size(k0,2)

                    i = 1;

                    tt = [0];
                    TT_1 = [tumours.T0(j)];
                    TT_2 = [0];
                    TT_3 = [0];
                    TT_4 = [0];
                    TT_5 = [tumours.V0(j)];
                    TT_6 = [tumours.c0(j)];
                    TT_7 = [1];
                    TT_8 = [0];

                 
                    while i <= num_frac_RT(k+1)

                        
                         
                            % RT
                            t_1 = linspace(tt(end),...
                                tt(end) + time_treat , ...
                                20);

                            IC = [TT_1(end), TT_2(end), TT_3(end),...
                                TT_4(end),TT_5(end), TT_6(end), ...
                                TT_7(end),TT_8(end)];

                            [tt_1,TT] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j),...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(1),k2,R(k+1)),t_1,IC, options);
                           
                           
                             % Between HT and RT
                             
                             t_2 = linspace(tt_1(end),...
                                 tt_1(end) + time_btw_HT_RT(n),...
                                 50);

                            IC_2 = [TT(end,1), TT(end,2), TT(end,3),...
                                TT(end,4),TT(end,5), TT(end,6),...
                                TT(end,7),TT(end,8)];

                            [tt_2,TTb] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_2,IC_2, options);
                             
                            % HT                                    
                            t_3 = linspace(tt_2(end),tt_2(end) + t_high, 30);

                            IC_3 = [TTb(end,1), TTb(end,2), TTb(end,3),TTb(end,4),TTb(end,5), TTb(end,6), TTb(end,7),TTb(end,8)];

                            [tt_3,TTc] = ode45(@(t,T) HT_high_RT_repair(...
                                        t, T, K, c_min,q2(j),q2sl(j), ...
                                        q1(j),q1sl(j),q3(j),q3sl(j), g, ...
                                        d1(j),d1sl(j),b(l), k0(m),eta_H,...
                                        l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                        k1(l),k2,R(1)),t_3,IC_3, options);
                            
                            % Post-HT tumour growth
                           
                            time_break = 2.88e3;        
                                                         
                            t_4 = linspace(tt_3(end), tt_3(end) + ...
                                (time_btw_frac_RT(3) - time_treat - ...
                                t_high - time_btw_HT_RT(n) + time_break),...
                                500);

                            IC_4 =[TTc(end,1), TTc(end,2), TTc(end,3),...
                                TTc(end,4),TTc(end,5), TTc(end,6),...
                                TTc(end,7),TTc(end,8)];

                            [tt_4,TTd] = ode45(@(t,T) HT_high_RT_repair(...
                                         t, T, K, c_min,q2(j),q2sl(j), ...
                                         q1(j),q1sl(j),q3(j),q3sl(j),g,...
                                         d1(j),d1sl(j),b(1),k0(m),eta_H,...
                                         l1,l2,l2sl,zeta,eta_R,mu,mu_v,...
                                         k1(1),k2,R(1)),t_4,IC_4, options);

                            tt = vertcat(tt,[tt_1;tt_2;tt_3;tt_4]);
                            TT_1 = vertcat(TT_1, ...
                                [TT(:,1); TTb(:,1);TTc(:,1);TTd(:,1)]);
                            TT_2 = vertcat(TT_2, ...
                                [TT(:,2); TTb(:,2);TTc(:,2);TTd(:,2)]);
                            TT_3 = vertcat(TT_3, ...
                                [TT(:,3); TTb(:,3);TTc(:,3);TTd(:,3)]);
                            TT_4 = vertcat(TT_4, ...
                                [TT(:,4); TTb(:,4);TTc(:,4);TTd(:,4)]);
                            TT_5 = vertcat(TT_5, ...
                                [TT(:,5); TTb(:,5);TTc(:,5);TTd(:,5)]);
                            TT_6 = vertcat(TT_6, ...
                                [TT(:,6); TTb(:,6);TTc(:,6);TTd(:,6)]);
                            TT_7 = vertcat(TT_7, ...
                                [TT(:,7); TTb(:,7);TTc(:,7);TTd(:,7)]);
                            TT_8 = vertcat(TT_8, ...
                                [TT(:,8); TTb(:,8);TTc(:,8);TTd(:,8)]);

                            i = i+1;
          
                    end
                end 
            end 
        end 
    end 
end 

